{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:5.0",
                "name": "python-idna",
                "purl": "pkg:rpm/vmware/python-idna?distro=photon-5"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "3.3-4.ph5"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Photon OS:5.0",
                "name": "frr",
                "purl": "pkg:rpm/vmware/frr?distro=photon-5"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "9.1-3.ph5"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Photon OS:5.0",
                "name": "python3-idna",
                "purl": "pkg:rpm/vmware/python3-idna?distro=photon-5"
            }
        }
    ],
    "id": "PHSA-2025-5.0-0462",
    "modified": "2025-04-07T09:29:43Z",
    "published": "2025-01-28T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-5.0-462"
        }
    ],
    "related": [
        "CVE-2024-3651",
        "CVE-2024-55553"
    ]
}